on:
  push:
    tags:
      - 'v*.*.*'

name: release

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        container:
          - { os: 'ubuntu-24.04', rust_target: 'aarch64-unknown-linux-musl' }
          - { os: 'ubuntu-24.04', rust_target: 'x86_64-unknown-linux-musl' }
          - { os: 'macos-latest', rust_target: 'x86_64-apple-darwin' }
          - { os: 'macos-latest', rust_target: 'aarch64-apple-darwin' }
    runs-on: "${{ matrix.container.os }}"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.container.rust_target }}"
      - run: cargo install cross --locked
      - run: cross build --release --target ${{ matrix.container.rust_target }}
      - name: Build and push
        run: |
          cp target/${{ matrix.container.rust_target }}/release/easypwned target/${{ matrix.container.rust_target }}/release/easypwned_${{ matrix.container.rust_target }}
          cp target/${{ matrix.container.rust_target }}/release/easypwned_haveibeenpwned_downloader target/${{ matrix.container.rust_target }}/release/easypwned_haveibeenpwned_downloader_${{ matrix.container.rust_target }}
      - name: Prepare output artifact (easypwned)
        uses: actions/upload-artifact@v7
        with:
          name: easypwned-${{ matrix.container.rust_target }}
          path: |
            target/${{ matrix.container.rust_target }}/release/easypwned_${{ matrix.container.rust_target }}
            target/${{ matrix.container.rust_target }}/release/easypwned_haveibeenpwned_downloader_${{ matrix.container.rust_target }}

  release:
     name: Release
     runs-on: ubuntu-24.04
     needs: ["build"]
     steps:
       - name: download artifacts
         uses: actions/download-artifact@v8
         with:
           path: binaries
       - name: Release
         uses: softprops/action-gh-release@v3
         with:
           fail_on_unmatched_files: true
           files: |
             binaries/*/*

  docker_build:
   name: docker
   runs-on: ubuntu-24.04
   needs: ["build"]
   strategy:
     fail-fast: true
     matrix:
       container:
         - { os: 'ubuntu-24.04', arch: 'arm64', rust_target: 'aarch64-unknown-linux-musl' }
         - { os: 'ubuntu-24.04', arch: 'amd64', rust_target: 'x86_64-unknown-linux-musl' }
   steps:
     - uses: actions/checkout@v6
     - uses: docker/setup-buildx-action@v4
       id: buildx
       with:
         install: true
     - name: Login to DockerHub
       uses: docker/login-action@v4
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: download artifacts
       uses: actions/download-artifact@v8
       with:
         path: binaries
     - name: Build and push
       run: |
         cp binaries/easypwned-${{ matrix.container.rust_target }}/easypwned_${{ matrix.container.rust_target }} binary_easypwned
         chmod +x binary_easypwned
         cp binaries/easypwned-${{ matrix.container.rust_target }}/easypwned_haveibeenpwned_downloader_${{ matrix.container.rust_target }} binary_easypwned_haveibeenpwned_downloader
         chmod +x binary_easypwned_haveibeenpwned_downloader
         docker buildx build -o type=docker --platform linux/${{ matrix.container.arch }} -t easybill/easypwned:${{github.ref_name}}_${{ matrix.container.arch }} .
         docker push easybill/easypwned:${{github.ref_name}}_${{ matrix.container.arch }}

  docker_manifest:
    name: Docker Image
    runs-on: ubuntu-24.04
    needs: ["docker_build"]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push manifest
        run: |
          docker manifest create easybill/easypwned:${{github.ref_name}} easybill/easypwned:${{github.ref_name}}_amd64 easybill/easypwned:${{github.ref_name}}_arm64
          docker manifest push easybill/easypwned:${{github.ref_name}}
